<?php
function commerce_compu_form_commerce_product_product_form_alter(&$form, &$form_state, $product) {
    if (!civicrm_initialize()) {
        return;
    }
    $product = $form_state['commerce_product'];
    $dao = new CRM_Member_DAO_MembershipType();
    
    $dao->orderBy('weight');
    $dao->find();
    $membershipTypes = array();
    while ($dao->fetch()) {
        $membershipTypes[$dao -> id] = $dao -> name;
    }
    $form['grantmember'] = array(
        '#type' => 'select',
        '#title' => t('Membership type'),
        '#default_value' => $product -> grantmember,
        '#options' => $membershipTypes,
        '#required' => false,
        '#description' => t('If a membership granted to purchaser after putting an order'),
    );
    $form['actions']['submit']['#submit'][] = 'commerce_compu_form_commerce_product_product_form_submit';
    
    return $form;
}

function commerce_compu_form_commerce_product_product_form_submit (&$form, &$form_state) {
    //global $user;
    
    //commerce_product_product_form_submit($form, $form_state);
    $product = &$form_state['commerce_product'];
    $product->grantmember = $form_state['values']['grantmember'];
    field_attach_submit('commerce_product', $product, $form, $form_state);
    
    // Save the product.
    commerce_product_save($product);
    
}

function commerce_compu_grant_membership_on_ordercomplete($order) {
  if (!civicrm_initialize()) {
    return;
  }

  // Find or create a CiviCRM contact ID for the customer.
  $cid = _commerce_civicrm_get_cid($order);
  foreach ($order->commerce_line_items['und'] as $line) {
      $line_item = commerce_line_item_load($line['line_item_id']);
      foreach ($line_item ->commerce_product['und'] as $lineitemUN) {
          $product_id = $lineitemUN['product_id'];
          $product = commerce_product_load($product_id);
          
          if ($product && $product -> grantmember) {
              civicrm_api3 ('Membership', 'create',array('membership_type_id' => $product -> grantmember, 'contact_id' => $cid, 'status_id' => 1));
          }
      }
  }
}